---
hosts:
  - host: ocp-app-node1 
  - host: ocp-infra-node1
  - host: ocp-infra-node2
  - host: ocp-support-node1
  - host: ocp-etcd1       
  - host: ocp-etcd2       
  - host: ocp-etcd3     
  - host: ocp-master1     
  - host: ocp-master2     
  - host: ocp-master3
